import { useState } from 'react'
import Head from 'next/head'
import Hero from '../components/Hero'
import Snowfall from 'react-snowfall'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [flakes, setFlakes] = useState(0);
  const [flakesColor, setFlakesColor] = useState('#fff');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Snowfall 
        color={flakesColor}
        style={{ }}
        snowflakeCount={flakes * 5}
      />

      <Hero />

      <input type="range" value={ flakes } onChange={ (e) => setFlakes(e.target.value) }/>
      <input type="color" value={ flakesColor } onChange={ (e) => setFlakesColor(e.target.value) } defaultValue="white"/>

      <button onClick={() => console.log(flakesColor)}>Click</button>
    </div>
  )
}
